name: CI - Run API Tests

on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      marker:
        description: 'Marker de pytest: -m <mark>'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Establecer variables de entorno desde secrets
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
        echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar tests con pytest y generar reporte Allure
      run: |
        pytest --disable-warnings -v ${{ github.event.inputs.marker }} --alluredir=reports/allure-results

    - name: Subir reporte aunque haya fallos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports/allure-results

    - name: Generar reporte HTML de Allure
      run: allure generate reports/allure-results --clean -o reports/allure-report-html
    
    - name: Publicar reporte Allure en GitHub Pages
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports/allure-report-html
        publish_branch: gh-pages
