name: Run Sylius API Tests

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Establecer variables de entorno
      run: |
        echo "BASE_URL=https://demo.sylius.com/api/v2" >> $GITHUB_ENV
        echo "ADMIN_USERNAME=sylius@example.com" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=sylius" >> $GITHUB_ENV

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas con Pytest y generar resultados Allure
      run: |
        pytest tests/ --disable-warnings -v --alluredir=reports/allure-results

    - name: Subir resultados Allure como artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports/allure-results

    - name: Instalar Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
        tar -xvzf allure-2.34.1.tgz
        sudo mv allure-2.34.1 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Generar reporte HTML de Allure
      run: |
        allure generate reports/allure-results --clean -o reports/allure-report-html

    - name: Subir reporte HTML como artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-html
        path: reports/allure-report-html