name: CI - Run API Tests

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código
    - name: Checkout código
      uses: actions/checkout@v4

    # 2. Configurar Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # 3. Inyectar variables sensibles desde Secrets
    - name: Establecer variables de entorno desde secrets
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
        echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> $GITHUB_ENV

    # 4. Instalar dependencias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 5. Ejecutar tests y generar resultados Allure
    - name: Ejecutar tests con pytest y generar reporte Allure
      #run: pytest --maxfail=3 --disable-warnings -v --alluredir=reports/allure-results
      run: pytest tests/catalog/inventory --maxfail=3 --disable-warnings -v --alluredir=reports/allure-results

    # 6. Subir resultados Allure como artifact
    - name: Subir reporte Allure como artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports/allure-results